version: '3.9'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - botvolumes:/var/bot
  manager:
    build: ./Manager
  bot:
    build: ./Bot

volumes:
  botvolumes: {}