version: '3'

services:
  db:
    image: mongo:4
    ports:
      - "27017:27017"
  manager: 
    build: ./manager
    expose:
      - "3003"
  order:
    build: ./order
    expose:
      - "3002"
  auth:
    build: ./auth
    expose:
      - "3001"
  app:
    build: ./flaskbotapi
    depends_on:
      - auth
    expose:
      - "3031"
  server:
    build: ./server
    depends_on:
      - app
    ports:
      - "80:80"
  client:
    build: ./front
    depends_on:
      - server
    ports:
      - "3000:3000"
