version: '3'

services:
  db:
    image: mongo
    expose:
      - "27017"
  manager:
    build: ./manager
    expose:
      - "3002"
  auth:
    build: ./auth
    expose:
      - "3001"
  app:
    build: ./flaskbotapi
    depends_on:
      - manager
      - auth
    expose:
      - "3031"
  server:
    build: ./server
    depends_on:
      - app
    ports:
      - "80:80"
  client:
    build: ./client
    depends_on:
      - server
    expose:
      - "3000"
